openapi: 3.2.0
info:
  title: Global Sports Data Lookup API v1 League Endpoints API
  description: This page contains all Lookup API endpoints that are part of our Core Sports Data.
  version: '1'
servers:
- url: /proxy/sports
tags:
- name: League Endpoints
paths:
  /gsd/lookup/v1/leagues/{leagueId}:
    get:
      tags:
      - League Endpoints
      summary: League Info
      operationId: LeagueInfo
      parameters:
      - $ref: '#/components/parameters/ApiKeyQuery'
      - $ref: '#/components/parameters/AcceptHeader'
      - name: leagueId
        in: path
        required: true
        schema:
          type: string
          default: GN4704RJ2JE0GXJ
      - $ref: '#/components/parameters/LanguageQuery'
      responses:
        '200':
          description: Successful response
  /gsd/lookup/v1/leagues/{leagueId}/league-seasons:
    get:
      tags:
      - League Endpoints
      summary: League Seasons by League
      operationId: LeagueSeasonsbyLeague
      parameters:
      - $ref: '#/components/parameters/ApiKeyQuery'
      - $ref: '#/components/parameters/AcceptHeader'
      - name: leagueId
        in: path
        required: true
        schema:
          type: string
          default: GN4704RJ2JE0GXJ
      - $ref: '#/components/parameters/LanguageQuery'
      responses:
        '200':
          description: Successful response
  /gsd/lookup/v1/leagues/{leagueId}/structure:
    get:
      tags:
      - League Endpoints
      summary: Structure by League
      operationId: StructurebyLeague
      parameters:
      - $ref: '#/components/parameters/ApiKeyQuery'
      - $ref: '#/components/parameters/AcceptHeader'
      - name: leagueId
        in: path
        required: true
        schema:
          type: string
          default: GN4704RJ2JE0GXJ
      - $ref: '#/components/parameters/LanguageQuery'
      responses:
        '200':
          description: Successful response
  /gsd/lookup/v1/leagues/{leagueId}/schedule-results:
    get:
      tags:
      - League Endpoints
      summary: Schedule and Results by League
      operationId: ScheduleandResultsbyLeague
      parameters:
      - $ref: '#/components/parameters/ApiKeyQuery'
      - $ref: '#/components/parameters/AcceptHeader'
      - name: leagueId
        in: path
        required: true
        schema:
          type: string
          default: GN4704RJ2JE0GXJ
      - name: timeFrom
        in: query
        required: true
        description: 'Here you can define the lower bound of the time range, which follows the ISO time structure: yyyy-MM-ddTHH:mm:ssZ. The max range between timeFrom and timeTo is 10 days and timeFrom should be earlier than timeTo.'
        schema:
          type: datetime
          default: '2022-02-15T00:00:00'
      - name: timeTo
        in: query
        required: true
        description: 'Here you can define the upper bound of the time range, which follows the ISO time structure: yyyy-MM-ddTHH:mm:ssZ. The max range between timeFrom and timeTo is 10 days and timeFrom should be earlier than timeTo.'
        schema:
          type: datetime
          default: '2022-02-24T00:00:00'
      - $ref: '#/components/parameters/LanguageQuery'
      responses:
        '200':
          description: Successful response
  /gsd/lookup/v1/leagues/{leagueId}/standings:
    get:
      tags:
      - League Endpoints
      summary: Standings by League
      operationId: StandingsbyLeague
      parameters:
      - $ref: '#/components/parameters/ApiKeyQuery'
      - $ref: '#/components/parameters/AcceptHeader'
      - name: leagueId
        in: path
        required: true
        schema:
          type: string
          default: GN4704RJ2JE0GXJ
      - $ref: '#/components/parameters/LanguageQuery'
      responses:
        '200':
          description: Successful response
  /gsd/lookup/v1/leagues/{leagueId}/league-season-overall-classifications:
    get:
      tags:
      - League Endpoints
      summary: League Season and Overall Classifications by League
      operationId: LeagueSeasonandOverallClassificationsbyLeague
      parameters:
      - $ref: '#/components/parameters/ApiKeyQuery'
      - $ref: '#/components/parameters/AcceptHeader'
      - name: leagueId
        in: path
        required: true
        schema:
          type: string
          default: GN4704RJ2JE0GXJ
      - $ref: '#/components/parameters/LanguageQuery'
      responses:
        '200':
          description: Successful response
  /gsd/lookup/v1/leagues/{leagueId}/teams:
    get:
      tags:
      - League Endpoints
      summary: Teams by League
      operationId: TeamsbyLeague
      parameters:
      - $ref: '#/components/parameters/ApiKeyQuery'
      - $ref: '#/components/parameters/AcceptHeader'
      - name: leagueId
        in: path
        required: true
        schema:
          type: string
          default: GN4704RJ2JE0GXJ
      - $ref: '#/components/parameters/LanguageQuery'
      responses:
        '200':
          description: Successful response
  /gsd/lookup/v1/leagues/{leagueId}/teams/{teamId}/roster:
    get:
      tags:
      - League Endpoints
      summary: Team Roster by League and Team
      operationId: TeamRosterbyLeagueandTeam
      parameters:
      - $ref: '#/components/parameters/ApiKeyQuery'
      - $ref: '#/components/parameters/AcceptHeader'
      - name: leagueId
        in: path
        required: true
        schema:
          type: string
          default: GN4704RJ2JE0GXJ
      - name: teamId
        in: path
        required: true
        schema:
          type: string
          default: GNDDXMAJZPWET9S
      - $ref: '#/components/parameters/LanguageQuery'
      responses:
        '200':
          description: Successful response
  /gsd/lookup/v1/leagues/{leagueId}/teams/{teamId}/schedule-results:
    get:
      tags:
      - League Endpoints
      summary: Schedule and Results by League and Team
      operationId: ScheduleandResultsbyLeagueandTeam
      parameters:
      - $ref: '#/components/parameters/ApiKeyQuery'
      - $ref: '#/components/parameters/AcceptHeader'
      - name: leagueId
        in: path
        required: true
        schema:
          type: string
          default: GN4704RJ2JE0GXJ
      - name: teamId
        in: path
        required: true
        schema:
          type: string
          default: GNDDXMAJZPWET9S
      - name: timeFrom
        in: query
        required: true
        description: 'Here you can define the lower bound of the time range, which follows the ISO time structure: yyyy-MM-ddTHH:mm:ssZ. The max range between timeFrom and timeTo is 31 days and timeFrom should be earlier than timeTo.'
        schema:
          type: datetime
          default: '2022-04-01T00:00:00'
      - name: timeTo
        in: query
        required: true
        description: 'Here you can define the upper bound of the time range, which follows the ISO time structure: yyyy-MM-ddTHH:mm:ssZ. The max range between timeFrom and timeTo is 31 days and timeFrom should be earlier than timeTo.'
        schema:
          type: datetime
          default: '2022-05-01T00:00:00'
      - $ref: '#/components/parameters/LanguageQuery'
      responses:
        '200':
          description: Successful response
  /gsd/lookup/v1/leagues/{leagueId}/teams/{teamId}/stats:
    get:
      tags:
      - League Endpoints
      summary: Stats by League and Team
      operationId: StatsbyLeagueandTeam
      parameters:
      - $ref: '#/components/parameters/ApiKeyQuery'
      - $ref: '#/components/parameters/AcceptHeader'
      - name: leagueId
        in: path
        required: true
        schema:
          type: string
          default: GN4704RJ2JE0GXJ
      - name: teamId
        in: path
        required: true
        schema:
          type: string
          default: GNDDXMAJZPWET9S
      - $ref: '#/components/parameters/LanguageQuery'
      responses:
        '200':
          description: Successful response
  /gsd/lookup/v1/leagues/{leagueId}/persons/{personId}/stats:
    get:
      tags:
      - League Endpoints
      summary: Stats by League and Person
      operationId: StatsbyLeagueandPerson
      parameters:
      - $ref: '#/components/parameters/ApiKeyQuery'
      - $ref: '#/components/parameters/AcceptHeader'
      - name: leagueId
        in: path
        required: true
        schema:
          type: string
          default: GN4704RJ2JE0GXJ
      - name: personId
        in: path
        required: true
        schema:
          type: string
          default: GNE2661MZM6Z8W5
      - $ref: '#/components/parameters/LanguageQuery'
      responses:
        '200':
          description: Successful response
  /gsd/lookup/v1/leagues/{leagueId}/brackets:
    get:
      tags:
      - League Endpoints
      summary: Brackets by League
      operationId: BracketsbyLeague
      parameters:
      - $ref: '#/components/parameters/ApiKeyQuery'
      - $ref: '#/components/parameters/AcceptHeader'
      - name: leagueId
        in: path
        required: true
        schema:
          type: string
          default: GNA5MGHG2ZVX2RD
      - $ref: '#/components/parameters/LanguageQuery'
      responses:
        '200':
          description: Successful response
components:
  parameters:
    AcceptHeader:
      name: Accept
      in: header
      required: true
      schema:
        type: string
        enum:
        - application/json
        default: application/json
    ApiKeyQuery:
      name: api_key
      in: query
      required: true
      description: API key for authentication
      schema:
        type: string
    LanguageQuery:
      name: language
      in: query
      description: Language Code which will translate all translatable fields into the requested language.
      schema:
        type: string
        enum:
        - ''
        - ar-SA
        - cs-CZ
        - da-DK
        - de-DE
        - el-GR
        - en-GB
        - en-US
        - es-ES
        - fi-FI
        - fr-FR
        - hu-HU
        - it-IT
        - ja-JP
        - ko-KR
        - nb-NO
        - nl-BE
        - nl-NL
        - pl-PL
        - pt-BR
        - pt-PT
        - ro-RO
        - ru-RU
        - sv-SE
        - tr-TR
        - zh-CN
        - zh-HK
        default: en-GB
