openapi: 3.2.0
info:
  title: GVD API v3.06 Controlled Vocabulary API
  description: GVD API is designed for database ingestion, providing ability to retrieve updates on-demand for television schedule data and related information.
  version: '3.06'
servers:
- url: /proxy/gvd
tags:
- name: Controlled Vocabulary
paths:
  /v1/cv:
    get:
      summary: CV
      description: Returns the Controlled Vocabulary for Global Video Data.
      tags:
      - Controlled Vocabulary
      parameters:
      - $ref: '#/components/parameters/ApiKeyQuery'
      - $ref: '#/components/parameters/AcceptHeader'
      - name: updateId
        in: query
        required: true
        schema:
          type: string
          default: '0'
        description: Returns a Controlled Vocabulary object modified at or after updateId with all of the CV in a single object.
      - name: limit
        in: query
        required: true
        schema:
          type: string
          default: '10'
        description: Approximate maximum number of CV objects to be returned by API. Frequently should be 1.
      - name: id
        in: query
        required: false
        schema:
          type: string
          default: ''
        description: To lookup a CV object by its Gracenote ID. Use Lookup calls for QA and troubleshooting purposes only. Gracenote does not support lookup APIs for Client production environments.
      responses:
        '200':
          description: Successful response
      operationId: getV1Cv
      x-operation-id-source: derived
components:
  parameters:
    AcceptHeader:
      name: Accept
      in: header
      required: false
      schema:
        type: string
        default: application/json
    ApiKeyQuery:
      name: api_key
      in: query
      required: true
      schema:
        type: string
      description: API key for authentication
