openapi: 3.2.0
info:
  title: Global Sports Data Lookup API v1 Match Endpoints API
  description: This page contains all Lookup API endpoints that are part of our Core Sports Data.
  version: '1'
servers:
- url: /proxy/sports
tags:
- name: Match Endpoints
paths:
  /gsd/lookup/v1/matches/{matchId}:
    get:
      tags:
      - Match Endpoints
      summary: Match Info
      operationId: MatchInfo
      parameters:
      - $ref: '#/components/parameters/ApiKeyQuery'
      - $ref: '#/components/parameters/AcceptHeader'
      - name: matchId
        in: path
        required: true
        schema:
          type: string
          default: GN9JNTF07S0NS4Q
      - $ref: '#/components/parameters/LanguageQuery'
      responses:
        '200':
          description: Successful response
  /gsd/lookup/v1/matches/{matchId}/lineups:
    get:
      tags:
      - Match Endpoints
      summary: Lineups by Match
      operationId: LineupsbyMatch
      parameters:
      - $ref: '#/components/parameters/ApiKeyQuery'
      - $ref: '#/components/parameters/AcceptHeader'
      - name: matchId
        in: path
        required: true
        schema:
          type: string
          default: GN9JNTF07S0NS4Q
      - $ref: '#/components/parameters/LanguageQuery'
      responses:
        '200':
          description: Successful response
  /gsd/lookup/v1/matches/{matchId}/actions:
    get:
      tags:
      - Match Endpoints
      summary: Actions by Match
      operationId: ActionsbyMatch
      parameters:
      - $ref: '#/components/parameters/ApiKeyQuery'
      - $ref: '#/components/parameters/AcceptHeader'
      - name: matchId
        in: path
        required: true
        schema:
          type: string
          default: GN9JNTF07S0NS4Q
      - $ref: '#/components/parameters/LanguageQuery'
      - name: tags
        in: query
        required: false
        description: Comma-separated list of tags in order to filter the endpoint response on specific actions. For example filter on MAIN in a Football match to only get the main actions like goals, penalties, cards and substitutes.
        schema:
          type: string
          default: ''
      responses:
        '200':
          description: Successful response
  /gsd/lookup/v1/matches/{matchId}/team-stats:
    get:
      tags:
      - Match Endpoints
      summary: Team Stats by Match
      operationId: TeamStatsbyMatch
      parameters:
      - $ref: '#/components/parameters/ApiKeyQuery'
      - $ref: '#/components/parameters/AcceptHeader'
      - name: matchId
        in: path
        required: true
        schema:
          type: string
          default: GN9JNTF07S0NS4Q
      - $ref: '#/components/parameters/LanguageQuery'
      responses:
        '200':
          description: Successful response
  /gsd/lookup/v1/matches/{matchId}/person-stats:
    get:
      tags:
      - Match Endpoints
      summary: Person Stats by Match
      operationId: PersonStatsbyMatch
      parameters:
      - $ref: '#/components/parameters/ApiKeyQuery'
      - $ref: '#/components/parameters/AcceptHeader'
      - name: matchId
        in: path
        required: true
        schema:
          type: string
          default: GN9JNTF07S0NS4Q
      - $ref: '#/components/parameters/LanguageQuery'
      responses:
        '200':
          description: Successful response
  /gsd/lookup/v1/matches/{matchId}/classifications:
    get:
      tags:
      - Match Endpoints
      summary: Classifications by Match
      operationId: ClassificationsbyMatch
      parameters:
      - $ref: '#/components/parameters/ApiKeyQuery'
      - $ref: '#/components/parameters/AcceptHeader'
      - name: matchId
        in: path
        required: true
        schema:
          type: string
          default: GN9JNTF07S0NS4Q
      - $ref: '#/components/parameters/LanguageQuery'
      responses:
        '200':
          description: Successful response
  /gsd/lookup/v1/matches/{matchId}/previous-results:
    get:
      tags:
      - Match Endpoints
      summary: Previous Results by Match
      operationId: PreviousResultsbyMatch
      parameters:
      - $ref: '#/components/parameters/ApiKeyQuery'
      - $ref: '#/components/parameters/AcceptHeader'
      - name: matchId
        in: path
        required: true
        schema:
          type: string
          default: GN9JNTF07S0NS4Q
      - name: skip
        in: query
        required: true
        description: Skip this number of elements in the response. If provided, it must be a non-negative integer and it must be provided together with the limit parameter.
        schema:
          type: string
          default: '0'
      - name: limit
        in: query
        required: true
        description: Limit for the number of elements in the response. If provided, it must be a positive integer and it must be provided together with the skip parameter.
        schema:
          type: string
          default: '5'
      - $ref: '#/components/parameters/LanguageQuery'
      responses:
        '200':
          description: Successful response
components:
  parameters:
    AcceptHeader:
      name: Accept
      in: header
      required: true
      schema:
        type: string
        enum:
        - application/json
        default: application/json
    ApiKeyQuery:
      name: api_key
      in: query
      required: true
      description: API key for authentication
      schema:
        type: string
    LanguageQuery:
      name: language
      in: query
      description: Language Code which will translate all translatable fields into the requested language.
      schema:
        type: string
        enum:
        - ''
        - ar-SA
        - cs-CZ
        - da-DK
        - de-DE
        - el-GR
        - en-GB
        - en-US
        - es-ES
        - fi-FI
        - fr-FR
        - hu-HU
        - it-IT
        - ja-JP
        - ko-KR
        - nb-NO
        - nl-BE
        - nl-NL
        - pl-PL
        - pt-BR
        - pt-PT
        - ro-RO
        - ru-RU
        - sv-SE
        - tr-TR
        - zh-CN
        - zh-HK
        default: en-GB
