openapi: 3.2.0
info:
  title: GVD API v3.06 Video Popularity API
  description: GVD API is designed for database ingestion, providing ability to retrieve updates on-demand for television schedule data and related information.
  version: '3.06'
servers:
- url: /proxy/gvd
tags:
- name: Video Popularity
paths:
  /v1/video-popularity:
    get:
      summary: Video Popularity
      description: Assigns a numeric score to TV series and movies that represents the majority of the population's level of recognition of a video program.
      tags:
      - Video Popularity
      parameters:
      - $ref: '#/components/parameters/ApiKeyQuery'
      - $ref: '#/components/parameters/AcceptHeader'
      - name: updateId
        in: query
        required: true
        schema:
          type: string
          default: '0'
        description: Returns full snapshot of video popularity modified at or after updateId.
      - name: limit
        in: query
        required: true
        schema:
          type: string
          default: '10'
        description: Maximum number video popularity items to be returned by the API.
      - name: program_root_id
        in: query
        required: false
        schema:
          type: string
          default: ''
        description: GN root ID for the program. The main ID associated with the score for a given day. All GN context IDs associated with a GN root ID will have the same score for a given country.
      responses:
        '200':
          description: Successful response
      operationId: getV1VideoPopularity
      x-operation-id-source: derived
components:
  parameters:
    AcceptHeader:
      name: Accept
      in: header
      required: false
      schema:
        type: string
        default: application/json
    ApiKeyQuery:
      name: api_key
      in: query
      required: true
      schema:
        type: string
      description: API key for authentication
